apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: do-pvc-5g
  namespace: storage-smoke
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: do-block-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-tester
  namespace: storage-smoke
spec:
  containers:
  - name: app
    image: busybox:1.36
    command: ["sh","-c","set -e; echo hello-$(date) > /data/hello.txt; sync; sleep 3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: do-pvc-5g

