apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-internal-tls
  namespace: observability
spec:
  secretName: grafana-internal-tls
  issuerRef:
    kind: ClusterIssuer
    name: internal-ca
  dnsNames:
    - grafana.internal
