apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-internal-tls
  namespace: observability
spec:
  secretName: prometheus-internal-tls
  issuerRef:
    kind: ClusterIssuer
    name: internal-ca
  dnsNames:
    - prometheus.internal
