apiVersion: v1
kind: Service
metadata:
  name: osdu-file
  labels:
    app: osdu-file
spec:
  type: ClusterIP
  selector:
    app: osdu-file
  ports:
    - name: http
      port: 8080
      targetPort: 8080
