apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-file
  labels:
    app: osdu-file
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osdu-file
  template:
    metadata:
      labels:
        app: osdu-file
    spec:
      containers:
        - name: file
          # TÌM TAG TRONG REGISTRY VÀ THAY VÀO ĐÂY
          image: community.opengroup.org:5555/osdu/platform/system/file/core-plus-file-release:8531906d
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: osdu-core-env
            # Nạp thêm secret S3/MinIO cho File
            - secretRef:
                name: osdu-objectstore-secret
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/file"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: osdu-postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osdu-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "$(KEYCLOAK_ISSUER_URI)"
            - name: PARTITION_SERVICE_ENDPOINT
              value: "http://osdu-partition:8080"
            # Cấu hình MinIO
            - name: CLOUD_PROVIDER
              value: "minio"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10