resources:
  - vendor/csi-digitalocean-v4.15.0/crds.yaml
  - vendor/csi-digitalocean-v4.15.0/driver.yaml
  - vendor/csi-digitalocean-v4.15.0/snapshot-controller.yaml

patchesStrategicMerge:
  - patches/patch-storageclass-delete.yaml
  - patches/patch-storageclass-retain.yaml

