apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-indexer
spec:
  template:
    spec:
      containers:
        - name: indexer
          env:
            # Override OpenSearch to use proxy (Step 27)
            - name: ELASTIC_HOST
              value: "opensearch-proxy.osdu-data.svc.cluster.local"
            - name: OPENSEARCH_HOST
              value: "opensearch-proxy.osdu-data.svc.cluster.local"
            - name: OPENSEARCH_URL
              value: "http://opensearch-proxy.osdu-data.svc.cluster.local:9200"
            - name: SPRING_ELASTICSEARCH_REST_URIS
              value: "http://opensearch-proxy.osdu-data.svc.cluster.local:9200"
