apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-partition
spec:
  template:
    spec:
      containers:
        - name: partition
          image: community.opengroup.org:5555/osdu/platform/system/partition/core-plus-partition-release:923ea1cd
          env:
            # FIX 1: Xóa 'value' cũ của Base đi (gán null) để dùng được 'valueFrom' mới
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: null
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: KEYCLOAK_ISSUER_URI

            # Các biến khác
            - name: KEYCLOAK_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: KEYCLOAK_ISSUER_URI
            
            - name: SPRING_AUTOCONFIGURE_EXCLUDE
              value: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

          # Cập nhật Port
          ports:
            - name: http
              containerPort: 8080
            - name: mgmt
              containerPort: 8081

          # FIX 2: Xóa 'tcpSocket' cũ của Base đi (gán null) để dùng 'httpGet'
          readinessProbe:
            tcpSocket: null
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 6
