apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-partition
spec:
  template:
    spec:
      containers:
        - name: partition
          env:
            # Make Spring Security use Keycloak
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak.internal/realms/osdu"
