apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-partition
spec:
  revisionHistoryLimit: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-entitlements
spec:
  revisionHistoryLimit: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-storage
spec:
  revisionHistoryLimit: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-legal
spec:
  revisionHistoryLimit: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-schema
spec:
  revisionHistoryLimit: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-file
spec:
  revisionHistoryLimit: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-toolbox
spec:
  revisionHistoryLimit: 2
