apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-storage
spec:
  template:
    spec:
      containers:
        - name: storage
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: REDIS_PORT
            - name: CACHE_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: REDIS_HOST
            - name: CACHE_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: REDIS_PORT
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: REDIS_HOST
            - name: SPRING_DATA_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: REDIS_PORT
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: REDIS_PORT
            - name: REDIS_GROUP_HOST
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: REDIS_HOST
            - name: KEYCLOAK_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: KEYCLOAK_ISSUER_URI
            - name: OPENID_PROVIDER_URL
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: KEYCLOAK_ISSUER_URI
            - name: OPENID_PROVIDER_ISSUER
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: KEYCLOAK_ISSUER_URI
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: KEYCLOAK_ISSUER_URI
            - name: OPENID_PROVIDER_CLIENT_SECRET
              value: "dummy-secret-value"
            - name: OPENID_PROVIDER_SCOPES
              value: "openid profile email"
