apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-partition
spec:
  template:
    spec:
      containers:
        - name: partition
          env:
            - name: KEYCLOAK_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: KEYCLOAK_ISSUER_URI
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "$(KEYCLOAK_ISSUER_URI)"
            - name: PARTITION_POSTGRES_URL
              value: "jdbc:postgresql://osdu-postgres.osdu-data.svc.cluster.local:5432/partition"
            - name: PARTITION_POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: osdu-postgres-secret
                  key: POSTGRES_USER
            - name: PARTITION_POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osdu-postgres-secret
                  key: POSTGRES_PASSWORD
