apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo-internal-tls
  namespace: default
spec:
  secretName: echo-internal-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  dnsNames:
    - echo.internal

