apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osdu-toolbox
  template:
    metadata:
      labels:
        app: osdu-toolbox
    spec:
      containers:
        - name: toolbox
          image: nicolaka/netshoot:latest
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c"]
          args: ["sleep infinity"]
          # netshoot có sẵn: curl, jq, dig, nslookup, ping, nc, tcpdump, iperf, etc.
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
