apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: osdu-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.6
          args: ["start"]
          ports:
            - containerPort: 8080
            - containerPort: 9000  # Khai báo thêm port quản trị
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: keycloak-db
            - name: KC_DB_URL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: POSTGRES_DB
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: POSTGRES_PASSWORD

            # Ingress reverse proxy (nginx)
            - name: KC_PROXY
              value: edge
            - name: KC_PROXY_HEADERS
              value: xforwarded
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: keycloak.internal
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"

            # Health/metrics (hữu ích cho observability)
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"

          envFrom:
            - secretRef:
                name: keycloak-admin-secret

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000             # SỬA: Đổi từ 8080 sang 9000
            initialDelaySeconds: 60  # Tăng từ 30 lên 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000             # SỬA: Đổi từ 8080 sang 9000
            initialDelaySeconds: 180 # Tăng từ 60 lên 180
            periodSeconds: 10
