apiVersion: v1
kind: Service
metadata:
  name: osdu-storage
  labels:
    app: osdu-storage
spec:
  type: ClusterIP
  selector:
    app: osdu-storage
  ports:
    - name: http
      port: 8080
      targetPort: 8080
