apiVersion: v1
kind: Service
metadata:
  name: osdu-partition
  labels:
    app: osdu-partition
spec:
  type: ClusterIP
  selector:
    app: osdu-partition
  ports:
    - name: http
      port: 8080
      targetPort: 8080
