apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-partition
  labels:
    app: osdu-partition
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osdu-partition
  template:
    metadata:
      labels:
        app: osdu-partition
    spec:
      containers:
        - name: partition
          image: community.opengroup.org:5555/osdu/platform/system/partition/core-plus-partition-release:923ea1cd
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: mgmt
          envFrom:
            - configMapRef:
                name: osdu-core-env
            - secretRef:
                name: osdu-core-secrets
          env:
            # Keep these "service-specific" values in the Deployment
            - name: CLOUD_PROVIDER
              value: "minio"
            - name: PARTITION_AUTH_ENABLED
              value: "false"
            - name: PARTITION_API
              value: "core-plus"
            - name: PARTITION_OAUTH2_CLIENT_ID
              value: "partition-service"
            - name: PARTITION_OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: osdu-core-secrets
                  key: partition-client-secret
            - name: PARTITION_OAUTH2_ENDPOINT
              value: "http://keycloak.internal/realms/osdu/protocol/openid-connect/token"

          # The app exposes a management web server on 8081.
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
