apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-entitlements
  labels:
    app: osdu-entitlements
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osdu-entitlements
  template:
    metadata:
      labels:
        app: osdu-entitlements
    spec:
      containers:
        - name: entitlements
          image: community.opengroup.org:5555/osdu/platform/security-and-compliance/entitlements/core-plus-entitlements-v2-release:9e5865f1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: osdu-core-env
          env:
            # --- KHAI BÁO CÁC BIẾN GỐC ---
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: POSTGRES_PORT
            - name: KEYCLOAK_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: osdu-core-env
                  key: KEYCLOAK_ISSUER_URI
            # -----------------------------
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/entitlements"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: osdu-postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osdu-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "$(KEYCLOAK_ISSUER_URI)"
            - name: PARTITION_API
              value: "http://osdu-partition:8080"
            - name: ENTITLEMENTS_AUTH_ENABLED
              value: "false"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
