apiVersion: v1
kind: Service
metadata:
  name: osdu-entitlements
  labels:
    app: osdu-entitlements
spec:
  type: ClusterIP
  selector:
    app: osdu-entitlements
  ports:
    - name: http
      port: 8080
      targetPort: 8080
