apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rook-ceph
resources:
  - ../../base
  - cephcluster.yaml
  - objectstore.yaml
  - objectstore-user.yaml
  - rgw-cert.yaml
  - rgw-ingress.yaml
