apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rgw
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  tls:
    - hosts: ["s3.internal"]
      secretName: rgw-internal-tls
  rules:
    - host: s3.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rook-ceph-rgw-osdu-store
                port:
                  number: 80
