apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rgw-internal-tls
spec:
  secretName: rgw-internal-tls
  dnsNames:
    - s3.internal
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
