apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-internal-tls
  namespace: argocd
spec:
  secretName: argocd-internal-tls
  issuerRef:
    kind: ClusterIssuer
    name: internal-ca
  dnsNames:
    - argocd.internal
