apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base
  - argocd-certificate.yaml
  - argocd-ingress.yaml

patches:
  - path: patches/patch-argocd-cm.yaml
  - path: patches/patch-argocd-cmd-params.yaml
