apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{},"name":"echo","namespace":"default"},"spec":{"ingressClassName":"nginx","rules":[{"host":"echo.internal","http":{"paths":[{"backend":{"service":{"name":"echo","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
  creationTimestamp: "2025-12-25T05:48:50Z"
  generation: 1
  name: echo
  namespace: default
  resourceVersion: "438732"
  uid: 8ea72b61-67bf-4876-83b1-609105e0abc8
spec:
  ingressClassName: nginx
  rules:
  - host: echo.internal
    http:
      paths:
      - backend:
          service:
            name: echo
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - ip: 10.118.0.6
    - ip: 10.118.0.7
