apiVersion: v1
kind: Service
metadata:
  name: osdu-schema
  labels:
    app: osdu-schema
spec:
  type: ClusterIP
  selector:
    app: osdu-schema
  ports:
    - name: http
      port: 8080
      targetPort: 8080
