apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-legal
  labels:
    app: osdu-legal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osdu-legal
  template:
    metadata:
      labels:
        app: osdu-legal
    spec:
      containers:
        - name: legal
          # TÌM TAG TRONG REGISTRY VÀ THAY VÀO ĐÂY
          image: community.opengroup.org:5555/osdu/platform/security-and-compliance/legal/core-plus-legal-release:340be643
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: osdu-core-env
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://$(POSTGRES_HOST):$(POSTGRES_PORT)/legal"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: osdu-postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osdu-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "$(KEYCLOAK_ISSUER_URI)"
            - name: PARTITION_SERVICE_ENDPOINT
              value: "http://osdu-partition:8080"
            - name: LEGAL_AUTH_ENABLED
              value: "false"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
