apiVersion: v1
kind: Service
metadata:
  name: osdu-legal
  labels:
    app: osdu-legal
spec:
  type: ClusterIP
  selector:
    app: osdu-legal
  ports:
    - name: http
      port: 8080
      targetPort: 8080
