apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: osdu-postgres
  namespace: osdu-data
spec:
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: do-block-storage-retain

