apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: osdu-postgres
  namespace: osdu-data
spec:
  template:
    spec:
      initContainers:
        - name: init-pgdata-dir
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              set -eux
              mkdir -p /mnt/pgdata
              chown -R 999:999 /mnt/pgdata
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /mnt

      containers:
        - name: postgres
          # ✅ “neutralize” nếu trước đó bạn set PGDATA=/var/lib/postgresql/data/pgdata
          # (giờ ta mount subPath rồi, để PGDATA default cho chắc)
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata

