apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-legal
spec:
  template:
    spec:
      containers:
        - name: legal
          env:
            - name: LEGAL_AUTH_ENABLED
              value: "false"
            - name: SERVICE_SECURITY_ENABLED
              value: "false"
            - name: SPRING_AUTOCONFIGURE_EXCLUDE
              value: "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration"
            - name: SECURITY_HTTPS_CERTIFICATE_TRUST
              value: "false"
            - name: SERVER_SSL_ENABLED
              value: "false"
            - name: SECURITY_REQUIRE_SSL
              value: "false"
            - name: SERVER_TOMCAT_REMOTEIP_PROTOCOL_HEADER_HTTPS_VALUE
              value: "http"
