apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-schema
spec:
  template:
    spec:
      containers:
        - name: schema
          env:
            - name: SCHEMA_AUTH_ENABLED
              value: "false"
