apiVersion: apps/v1
kind: Deployment
metadata:
  name: osdu-file
spec:
  template:
    spec:
      containers:
        - name: file
          env:
            - name: FILE_AUTH_ENABLED
              value: "false"
