apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: internal-ca
  creationTimestamp: "2025-12-27T15:13:01Z"
  generation: 1
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: kps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.7.0
    chart: kube-prometheus-stack-80.7.0
    heritage: Helm
    release: kps
  name: kps-kube-prometheus-stack-alertmanager
  namespace: observability
  resourceVersion: "576302"
  uid: 25eb26e7-e998-47ae-a53d-26bc76d5a099
spec:
  ingressClassName: nginx
  rules:
  - host: alertmanager.internal
    http:
      paths:
      - backend:
          service:
            name: kps-kube-prometheus-stack-alertmanager
            port:
              number: 9093
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - alertmanager.internal
    secretName: alertmanager-internal-tls
status:
  loadBalancer:
    ingress:
    - ip: 10.118.0.6
    - ip: 10.118.0.7
