apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-12-27T15:13:00Z"
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: kps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.7.0
    chart: kube-prometheus-stack-80.7.0
    heritage: Helm
    release: kps
    self-monitor: "true"
  name: kps-kube-prometheus-stack-alertmanager
  namespace: observability
  resourceVersion: "576078"
  uid: e7beb929-dcd3-4380-8fde-e3fab0f7848b
spec:
  clusterIP: 10.100.213.101
  clusterIPs:
  - 10.100.213.101
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    port: 9093
    protocol: TCP
    targetPort: 9093
  - appProtocol: http
    name: reloader-web
    port: 8080
    protocol: TCP
    targetPort: reloader-web
  selector:
    alertmanager: kps-kube-prometheus-stack-alertmanager
    app.kubernetes.io/name: alertmanager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
