apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-12-27T15:13:00Z"
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 80.7.0
    chart: kube-prometheus-stack-80.7.0
    heritage: Helm
    release: kps
    self-monitor: "true"
  name: kps-kube-prometheus-stack-prometheus
  namespace: observability
  resourceVersion: "576084"
  uid: 99ab197e-a4e2-4d5a-a3ef-8eb74a4c7e65
spec:
  clusterIP: 10.105.2.83
  clusterIPs:
  - 10.105.2.83
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http-web
    port: 9090
    protocol: TCP
    targetPort: 9090
  - appProtocol: http
    name: reloader-web
    port: 8080
    protocol: TCP
    targetPort: reloader-web
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: kps-kube-prometheus-stack-prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
