apiVersion: v1
kind: Service
metadata:
  name: opensearch-proxy
  namespace: osdu-data
  labels:
    app: opensearch-proxy
spec:
  selector:
    app: opensearch-proxy
  ports:
  - port: 9200
    targetPort: 9200
    name: http
