apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: do-block-storage-retain
  annotations:
#    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
